using System.Text;
using IconTrim.Core.Abstractions;
using IconTrim.Core.Models;

namespace IconTrim.BootstrapIcons;

/// <summary>Produces Bootstrap Icons class rules for the selected subset font.</summary>
public sealed class BootstrapIconsCssGenerator : ICssGenerator
{
    /// <summary>Builds a CSS font-face rule and one content rule per selected icon.</summary>
    /// <param name="icons">Definitions included in the generated font.</param>
    /// <param name="fontUrl">Public versioned WOFF2 URL written into CSS.</param>
    /// <returns>Complete CSS text for the selected icons.</returns>
    public string Generate(IReadOnlyCollection<IconDefinition> icons, string fontUrl)
    {
        var builder = new StringBuilder();
        builder.AppendLine("/*");
        builder.AppendLine(" * AUTO-GENERATED FILE.");
        builder.AppendLine(" * Do not edit manually.");
        builder.AppendLine(" * Generated by IconTrim.");
        builder.AppendLine($" * Generated at: {DateTimeOffset.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        builder.AppendLine($" * Icons: {icons.Count}");
        builder.AppendLine($" * Font: {fontUrl}");
        builder.AppendLine(" */");
        builder.AppendLine();
        builder.AppendLine("@font-face {");
        builder.AppendLine("    font-display: block;");
        builder.AppendLine("    font-family: \"bootstrap-icons\";");
        builder.AppendLine($"    src: url(\"{fontUrl}\") format(\"woff2\");");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine(".bi::before, [class^=\"bi-\"]::before, [class*=\" bi-\"]::before {");
        builder.AppendLine("    display: inline-block;");
        builder.AppendLine("    font-family: \"bootstrap-icons\" !important;");
        builder.AppendLine("    font-style: normal;");
        builder.AppendLine("    font-weight: normal !important;");
        builder.AppendLine("    font-variant: normal;");
        builder.AppendLine("    text-transform: none;");
        builder.AppendLine("    line-height: 1;");
        builder.AppendLine("    vertical-align: -.125em;");
        builder.AppendLine("    -webkit-font-smoothing: antialiased;");
        builder.AppendLine("    -moz-osx-font-smoothing: grayscale;");
        builder.AppendLine("}");
        builder.AppendLine();
        foreach (var icon in icons.OrderBy(x => x.Name, StringComparer.OrdinalIgnoreCase))
            builder.Append('.').Append(icon.Name).Append("::before { content: \"\\")
                .Append(icon.UnicodeHex.ToLowerInvariant()).AppendLine("\"; }");
        return builder.ToString();
    }
}
